services:
  ollama-webui-qwen3:
    image: harbor.suanleme.cn/docsify/ollama-webui-qwen3:v20250528
    build: .
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "8080:8080"
      - "11434:11434"

